services:
  - type: web
    name: utdrs-frontend
    env: docker
    repo: https://github.com/yourusername/utdrs-frontend.git  # Update with your repo
    branch: main
    dockerfilePath: ./Dockerfile
    dockerContext: .
    envVars:
      - key: NODE_ENV
        value: production
